

export const postCategories = ['Workout Plan', 'Meal Plan', 'Photos', 'Others']

export const eventCategories = ['basketball', 'soccer', 'jogging', 'yoga', 'biking', 'select a category', 'none']

export const newCats = [
  {'Fitness': [
    'Aerial',
    'Aerobics',
    'Barre',
    'Boxing',
    'Circuit Training',
    'Core',
    'Crossfit',
    'Indoor Cycling',
    'Kettleball',
    'Kickboxing',
    'Martial Arts',
    'Other Fitness',
    'Prenatal Fitness',
    'Suspension Training',
    'Swimming',
    'Weight Lifting',
    'Zumba',
  ]},
  {'Wellness':[
    'Meditation',
    'Other Wellness',
    'Pilates',
    'Tai Chi',
    'Yoga',
  ]},
  {'Sports': [
    'Badminton',
    'Baseball',
    'Basketball',
    'Boxing',
    'Bowling',
    'Cheerleading',
    'Cricket',
    'Curling',
    'Disc Sports',
    'Dodgeball',
    'Equestrian Sports',
    'Fencing',
    'Field Hockey',
    'Football',
    'Golf',
    'Gymnastics',
    'Handball',
    'Hockey',
    'Ice Hockey',
    'Kickball',
    'Lacrosse',
    'MMA',
    'Netball',
    'Other Sports',
    'Paintball',
    'Pingpong',
    'Racquetball',
    'Rowing',
    'Rugby',
    'Skating',
    'Soccer',
    'Softball',
    'Squash',
    'Table Tennis',
    'Tennis',
    'Trangleball',
    'Volleyball',
    'Water Polo',
    'Water Sports',
    'Wiffleball',
    'Winter Sports',
    'Wrestling',
  ]},
  {'Outdoor Adventure':[
    'Camping',
    'Canyoneering',
    'Canoeing',
    'Caving',
    'Climbing',
    'Fishing',
    'Gymnastics',
    'Hiking',
    'Hunting',
    'Ice Skating',
    'Kayaking',
    'Kite Surfing',
    'Mountain Biking',
    'Other Outdoors',
    'Paddleboarding',
    'Polo',
    'Rafting',
    'Sailing',
    'Skiing',
    'Skydiving',
    'Surfing',
    'Trail Running',
  ]},
  {'Endurance': [
    'Adventure Racing',
    'Cycling',
    'Duathlon',
    'Duathlon Training',
    'Marathon',
    'Marathon Training',
    'Other Endurance',
    'Running',
    'Swimming',
    'Trail Running',
    'Triathlon',
    'Triathlon Training',
    'Walking',
  ]},
  {'Dance':[
    'Bachata',
    'Ballet',
    'Belly Dance',
    'Cha Cha',
    'Country',
    'Cumbia',
    'East Coast Swing',
    'Fox Trot',
    'Hip Hop',
    'Jazz',
    'Jive',
    'Merengue',
    'Other Dance',
    'Paso Doble',
    'Quick Step',
    'Rumba',
    'Salsa',
    'Samba',
    'Tango',
    'Tap Dancing',
    'Waltz',
    'West Coast Swing',
    'Zumba',
  ]},
  {'Martial Arts': [
    'Aikido',
    'Boxing',
    'Brazilian Jiu Jitsu',
    'Caporeia',
    'Fencing',
    'Jiu Jitsu',
    'Judo',
    'Karate',
    'Kendo',
    'Kickboxing',
    'Krav Maga',
    'Kung Fu',
    'Muay Thai',
    'Ninjutsu',
    'Sambo',
    'Shaolin Kung Fu',
    'Sumo',
    'Taekwondo',
    'Wing Chun',
    'Wushu',
    'Wrestling',
  ]},
]

export const getNewCategories = () => {
  let i = 0;
  let data = [];
  newCats.forEach(c => {
    let label = Object.keys(c)[0];
    data.push({ key: i++, section: true, label });
    c[label].forEach(o => data.push({key: i++, label: o}));
  });
  return data;
}